export const PROJECTS = [
  {
    title: 'PIPELINE ZERO',
    category: 'cicd',
    tag: 'CI / CD',
    meta: 'A fully automated pipeline that ships from commit to production in minutes.',
    colorA: '#22c55e',
    colorB: '#60a5fa',
  },
  {
    title: 'TERRAFORM ATLAS',
    category: 'iac',
    tag: 'Infrastructure as Code',
    meta: 'Declarative infrastructure that reproduces an entire environment from one repo.',
    colorA: '#8b5cf6',
    colorB: '#60a5fa',
  },
  {
    title: 'KUBERNETES MESH',
    category: 'containers',
    tag: 'Containers & Orchestration',
    meta: 'A self-healing container fleet that scales itself before you notice the spike.',
    colorA: '#2dd4bf',
    colorB: '#60a5fa',
  },
  {
    title: 'SIGNAL TOWER',
    category: 'observability',
    tag: 'Observability',
    meta: 'Metrics, logs and traces unified into one pane of glass, in real time.',
    colorA: '#f59e0b',
    colorB: '#ec4899',
  },
  {
    title: 'CLOUD FORGE',
    category: 'cloud',
    tag: 'Cloud Infrastructure',
    meta: 'Multi-region cloud architecture designed for failure, not just uptime.',
    colorA: '#60a5fa',
    colorB: '#2dd4bf',
  },
  {
    title: 'ZERO TRUST VAULT',
    category: 'security',
    tag: 'DevSecOps',
    meta: 'Security scanned into every commit, not bolted on after the breach.',
    colorA: '#ec4899',
    colorB: '#8b5cf6',
  },
];
