export const PROJECTS = [
  {
    title: 'AURORA PROTOCOL',
    category: 'websites',
    tag: 'Brand Site',
    meta: 'A generative homepage that repaints itself around every visitor.',
    colorA: '#8b5cf6',
    colorB: '#ec4899',
  },
  {
    title: 'GLASS HORIZON',
    category: 'installations',
    tag: 'Installation',
    meta: 'A nine-screen lobby installation driven by real-time crowd motion.',
    colorA: '#2dd4bf',
    colorB: '#60a5fa',
  },
  {
    title: 'NEON ORACLE',
    category: 'xr',
    tag: 'XR / AI',
    meta: 'A conversational AI guide rendered as a volumetric mixed-reality being.',
    colorA: '#ec4899',
    colorB: '#f59e0b',
  },
  {
    title: 'VELVET ECHO',
    category: 'multiplayer',
    tag: 'Multiplayer',
    meta: 'A browser-native social space for a thousand concurrent strangers.',
    colorA: '#60a5fa',
    colorB: '#8b5cf6',
  },
  {
    title: 'PHANTOM CIRCUIT',
    category: 'games',
    tag: 'Game',
    meta: 'A WebGL puzzle-racer that ships as a single shareable link.',
    colorA: '#f59e0b',
    colorB: '#ec4899',
  },
  {
    title: 'SILENT ATLAS',
    category: 'websites',
    tag: 'Product Site',
    meta: 'An award-nominated launch site built around one looping hero shot.',
    colorA: '#2dd4bf',
    colorB: '#8b5cf6',
  },
];
